### PR TITLE
Added repository level readme

### PR DESCRIPTION
**Pull request by nkhedekar**

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@nkhedekar for ros-* repos, please wait for a review and approval from another maintainer.

**Comment by nkhedekar** [comment]
My bad, I thought this change was too minor. Will keep in mind :+1:

**Comment by SteveMacenski** [comment]
Its OK.

If you'd like run releases for Noetic / melodic, you can do that now. Make sure when you run bloom to enable the PR builder. That will give us CI for the time being. I gave you 3 the maintainer rights to the release repo below in ros-gbp

https://github.com/ros-gbp/perception_open3d-release

**Comment by SteveMacenski** [comment]
I just setup the webhooks so it'll run when enabled

**Pull request merged**
